polls/urls.py
from django.urls import path

from . import views
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    #path('', views.get_name, name='get_name'),
    path('head', views.header, name='header'),
    path('about', views.about, name='about'),
    path('xidmet', views.xidmet, name='xidmet'),
    path('contact', views.contact, name='contact'),
    path('luget', views.dictionary, name='dictionary'),
    path('learn', views.learn, name='learn'),

]

statistika/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include(('polls.urls','polls'),namespace='polls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

polls/models.py
from django.db import models
import datetime
from ckeditor.fields import RichTextField



# Create your models here.

class Post(models.Model):
    text = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.text


class Letter(models.Model):
    alpha = models.CharField(max_length=200,default='')
    alpha.alphabetic_filter = True

    def __str__(self):
        return self.alpha



class Word(models.Model):
    letter = models.ForeignKey(Letter, on_delete=models.CASCADE,default='',related_name = 'connect')
    word = models.CharField(max_length=200,default='')
    word_exp = models.TextField()

    def __str__(self):
        return self.word

class About(models.Model):
    title_a = models.CharField( max_length=100)
    content_a = models.TextField()
    title_a = RichTextField()
    content_a  =RichTextField()

    def __str__(self):
        return self.title_a

class Services(models.Model):
    title_s = models.CharField(max_length = 100)
    content_s = models.TextField()

    def __str__(self):
        return  self.title_s

class Learn(models.Model):
    title_l= models.CharField(max_length = 100)
    content_l = models.TextField()
    content_l = RichTextField()

    def __str__(self):
        return  self.title_l

polls/forms.py
from django import forms
from .models import Post


class NameForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

polls/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.core.mail import send_mail
from .models import Post,Letter,Word,About,Services,Learn
from django.core.mail import send_mail
from django.conf import settings
from django.utils.html import strip_tags
from .forms import NameForm
# Create your views here.


def index(request):
    return render(request, 'polls/index.html')


def header(request):
    return render(request, 'polls/header.html')

def about(request):
    about_list = About.objects.all()
    return render(request, 'polls/about.html', context = {'about_list':about_list})

def xidmet(request):
    #xidmet_list = Services.objects.all()
    xidmet_list = Services.objects.values()
    context = {'xidmet_list':xidmet_list}
    return render(request, 'polls/xidmet.html', context )

def contact(request):
    return render(request, 'polls/contact.html')

def dictionary(request):
    word_l = Letter.objects.all()
    word_e = Word.objects.all()
    context = {'word_l':word_l,'word_e':word_e}
    return render(request, 'polls/luget.html', context)

def learn(request):
    title = Learn.objects.values()
    #title_c = Learn.objects.values('content_l')
    context = {'title':title}
    return render(request, 'polls/oyren.html', context)

templates/polls/about.html
{% include 'polls/header.html' %}
<br><br>
<div class="container">
{% for about in about_list %}

<h2>{{about.title_a|safe}}</h2><hr>
<p>{{about.content_a|safe}}</p>

{% endfor %}
</div>
{% include 'polls/footer.html' %}

templates/polls/contact.html
{% include 'polls/header.html' %}

<style>

    </style>

    <div class="container contact">
        <div class="row">
        <div class="col-md-6">
            <div class="mektub">
                <i class="fa fa-envelope"></i>
                <h3 class="text-center">Məktub göndər</h3>
            </div>

        <form action="/contact.php">

                    <input type="email" id="fname" name="firstname" placeholder="E-poçt">



                    <input type="text" id="lname" name="lastname" placeholder="Məktubun mövzusu">


                <div class="col-75">
                    <textarea id="subject" name="subject" placeholder="Məktubun mətni" style="height:200px"></textarea>
                </div>
           <button type="button" class="btn"><i class="fa fa-send-o"></i> Göndər</button>
        </form>
    </div>

        <div class="col-md-6">
            <div class="unvan">
                <i class="fa fa-map-marker"></i>
                <h3 class="text-center">Ünvan</h3>
                <div id="map">

                </div>
                <p>Azərbaycan Respublikasının Dövlət Statistika Komitəsi <br>Bakı, AZ 1136, İnşaatçılar prospekti, 81<br>Faks : (+994 12) 538 24 42 Tel : (+994 12) 538 21 39</p>

                <script>
                    function initMap() {
                        var uluru = {lat: 40.383067, lng: 49.822208};
                        var map = new google.maps.Map(document.getElementById('map'), {
                            zoom: 16,
                            center: uluru
                        });
                        var marker = new google.maps.Marker({
                            position: uluru,
                            map: map
                        });
                    }
                </script>
                <script async defer
                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBwzEW5_pRCUx_Mk2yCq7kZhKoC0Be3Po4&callback=initMap">
                </script>

            </div>
        </div>
    </div>
    </div>


{% include 'polls/footer.html' %}

templates/polls/footer.html
<footer class="mainfooter" role="contentinfo">
  <div class="footer-middle">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Sütun 1</h4>
          <ul class="list-unstyled">
            <li><a href="#"></a></li>
            <li><a href="#">Payment Center</a></li>
            <li><a href="#">Contact Directory</a></li>
            <li><a href="#">Forms</a></li>
            <li><a href="#">News and Updates</a></li>
            <li><a href="#">FAQs</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Sütun 2</h4>
          <ul class="list-unstyled">
            <li><a href="#">Website Tutorial</a></li>
            <li><a href="#">Accessibility</a></li>
            <li><a href="#">Disclaimer</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">FAQs</a></li>
            <li><a href="#">Webmaster</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Sütun 3</h4>
          <ul class="list-unstyled">
            <li><a href="#">Parks and Recreation</a></li>
            <li><a href="#">Public Works</a></li>
            <li><a href="#">Police Department</a></li>
            <li><a href="#">Fire</a></li>
            <li><a href="#">Mayor and City Council</a></li>
            <li>
              <a href="#"></a>
            </li>
          </ul>
        </div>
      </div>
    	<div class="col-md-3">
    		<h4>Bizi izləyin</h4>
            <ul class="social-network social-circle">
             <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
             <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
            </ul>
		</div>
    </div>
	<div class="row">
		<div class="col-md-12 copy">
			<p class="text-center">&copy; Copyright 2018 - ETSIM.  Bütün hüquqları qorunur.</p>
		</div>
	</div>


  </div>
  </div>
</footer>




</body>
</html>

templates/polls/footer2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/polls/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <title>Statistical Information Portal</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
      <link href="{% static 'css/index.css' %}" rel="stylesheet">



   </head>
   <body>
      <div class="navbr">
         <div class=" container">
            <!-- <a href="#">Home</a>
               <a href="#">Search</a> -->
            <button type="button" class="btn btn-warning btn-sm">Daxil ol</button>
            <button type="button" class="btn btn-info btn-sm">Qeydiyyat</button>
         </div>
      </div>
      <div class="container logo-back">
         <div class="row main-logo">
            <div class="col-md-12 col-xs-12">


               <a class="" href="{% url 'polls:index' %}"><img src="{% static 'img/logo.png' %}"  class="main_logo img-responsive" width="319"></a>
            </div>
         </div>
      </div>
      <nav class="navbar navbar-expand-md sidebarNavigation">
         <div class="container">
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar top-bar"></span>
            <span class="icon-bar middle-bar"></span>
            <span class="icon-bar bottom-bar"></span>
            <span class="sr-only">Toggle navigation</span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
               <ul class="nav navbar-nav nav-flex-icons ">
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'polls:index' %}">Əsas səhifə</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'polls:about' %}">Haqqımızda</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'polls:xidmet' %}">Xidmətlər</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'polls:learn' %}">Statistika öyrən</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'polls:dictionary' %}">Statistik lüğət</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'polls:contact' %}">Əlaqə</a>
                  </li>
                  <!--  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                         aria-expanded="false">Dropdown</a>
                     <div class="dropdown-menu" aria-labelledby="dropdown01">
                         <a class="dropdown-item" href="#">Action</a>
                         <a class="dropdown-item" href="#">Another action</a>
                         <a class="dropdown-item" href="#">Something else here</a>
                     </div>
                     </li> -->
               </ul>
               <form class="mx-2 ml-auto d-inline w-30">
                  <div class="input-group">
                     <input type="text" class="form-control border border-right-0" placeholder="Axtar...">
                     <span class="input-group-append">
                     <button class="btn border border-left-0" type="button">
                     <i class="fa fa-search"></i>
                     </button>
                     </span>
                  </div>
               </form>
            </div>
         </div>
      </nav>
<script>
window.onload = function () {
   if (window.jQuery) {
      $(document).ready(function () {
         $(".sidebarNavigation .navbar-collapse").hide().clone().appendTo("body").removeAttr("class").addClass("sideMenu").show();
         $("body").append("<div class='overlay'></div>");
         $(".navbar-toggle, .navbar-toggler").on("click", function () {
            $(".sideMenu").addClass($(".sidebarNavigation").attr("data-sidebarClass"));
            $(".sideMenu, .overlay").toggleClass("open");
            $(".overlay").on("click", function () {
               $(this).removeClass("open");
               $(".sideMenu").removeClass("open")
            })
         });
         $("body").on("click", ".sideMenu.open .nav-item", function () {
            if (!$(this).hasClass("dropdown")) {
               $(".sideMenu, .overlay").toggleClass("open")
            }
         });
         $(window).resize(function () {
            if ($(".navbar-toggler").is(":hidden")) {
               $(".sideMenu, .overlay").hide()
            } else {
               $(".sideMenu, .overlay").show()
            }
         })
      })
   } else {
      console.log("sidebarNavigation Requires jQuery")
   }
}
</script>

templates/polls/header2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/polls/index.html
{% include 'polls/header.html' %}

{% include 'polls/slider.html' %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

<div class="container">
  <div class="services-cards">
  <h1>Xidmətlər</h1>
  <hr>
  <div class="row">
    <div class="col-md-4 col-sm-12">
      <div class="card mb-4">
        <div class="card-header text-center ">
          <h5>Analitik tədqiqatların təhlili</h5>
        </div>
        <div class="card-body">
            <div>
            <p>Pek çok araştırmanın başında Alfa (1.tip hata) 0.05 olarak kabul edilir. Yani hipotezde en fazla %5’lik bir hata öngörülmektedir.</p>

            <!-- MODAL BUTTON STARTS -->
          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
            Daha ətraflı
          </button>

          <!-- The Modal -->
          <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Regressiya analizi</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi, Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Bağla</button>
                </div>

              </div>
            </div>
          </div>
          <!--MODAL BUTTON ENDS  -->
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-12">
      <div class="card mb-4">
        <div class="card-header text-center ">
          <h5>Regresiya analizi</h5>
        </div>
        <div class="card-body">
            <div>
            <p>Pek çok araştırmanın başında Alfa (1.tip hata) 0.05 olarak kabul edilir. Yani hipotezde en fazla %5’lik bir hata öngörülmektedir.</p>

            <!-- MODAL BUTTON STARTS -->
          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
            Daha ətraflı
          </button>

          <!-- The Modal -->
          <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Regressiya analizi</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi, Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Bağla</button>
                </div>

              </div>
            </div>
          </div>
          <!--MODAL BUTTON ENDS  -->
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-12">
      <div class="card mb-4">
        <div class="card-header text-center ">
          <h5>Analitik tədqiqatların təhlili</h5>
        </div>
        <div class="card-body">
            <div>
            <p>Pek çok araştırmanın başında Alfa (1.tip hata) 0.05 olarak kabul edilir. Yani hipotezde en fazla %5’lik bir hata öngörülmektedir.</p>

            <!-- MODAL BUTTON STARTS -->
          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
            Daha ətraflı
          </button>

          <!-- The Modal -->
          <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Regressiya analizi</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi, Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Bağla</button>
                </div>

              </div>
            </div>
          </div>
          <!--MODAL BUTTON ENDS  -->
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-12">
      <div class="card mb-4">
        <div class="card-header text-center ">
          <h5>Analitik tədqiqatların təhlili</h5>
        </div>
        <div class="card-body">
            <div>
            <p>Pek çok araştırmanın başında Alfa (1.tip hata) 0.05 olarak kabul edilir. Yani hipotezde en fazla %5’lik bir hata öngörülmektedir.</p>

            <!-- MODAL BUTTON STARTS -->
          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
            Daha ətraflı
          </button>

          <!-- The Modal -->
          <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Regressiya analizi</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi, Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Bağla</button>
                </div>

              </div>
            </div>
          </div>
          <!--MODAL BUTTON ENDS  -->
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-12">
      <div class="card mb-4">
        <div class="card-header text-center ">
          <h5>Analitik tədqiqatların təhlili</h5>
        </div>
        <div class="card-body">
            <div>
            <p>Pek çok araştırmanın başında Alfa (1.tip hata) 0.05 olarak kabul edilir. Yani hipotezde en fazla %5’lik bir hata öngörülmektedir.</p>

            <!-- MODAL BUTTON STARTS -->
          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
            Daha ətraflı
          </button>

          <!-- The Modal -->
          <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Regressiya analizi</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi, Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Bağla</button>
                </div>

              </div>
            </div>
          </div>
          <!--MODAL BUTTON ENDS  -->
            </div>
        </div>
      </div>
    </div>
    <div class="col-md-4  col-sm-12">
      <div class="card mb-4">
        <div class="card-header text-center ">
          <h5>Analitik tədqiqatların təhlili</h5>
        </div>
        <div class="card-body">
            <div>
            <p>Pek çok araştırmanın başında Alfa (1.tip hata) 0.05 olarak kabul edilir. Yani hipotezde en fazla %5’lik bir hata öngörülmektedir.</p>

            <!-- MODAL BUTTON STARTS -->
          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
            Daha ətraflı
          </button>

          <!-- The Modal -->
          <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">Regressiya analizi</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi, Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,  Regressiya analizi,
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Bağla</button>
                </div>

              </div>
            </div>
          </div>
          <!--MODAL BUTTON ENDS  -->
            </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>

  <!-- End of row -->
{% include 'polls/footer.html' %}

templates/polls/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/polls/luget.html
{% include 'polls/header.html' %}

<div id="dict_scroll">
<div class="container">

   <div class="dict-tab">
 <h1>Statistik lüğət</h1>

      <ul class="tabs letters">
          {% for word in word_l %}
        <li><a href="#tab1">{{word.alpha}}</a></li>
{% endfor %}
      </ul>


<!-- A start-->
<div id="tab1" class="tab_content">

   <div class="container">
      <div class="row"><!-- row -->

        <div class="col-md-4 st">
<h3>Anlayışın adı</h3>
            <hr>
            <ul class="tabs sub-tab">
{% for word in word_e %}
               <!-- Add tabs here -->
               <a href="#tab1-1{{word.id}}">
                  <li>{{word.word}}</li>
               </a>
  {% endfor %}
            </ul>
         </div>
          <div class="col-md-8">
             <h3>Anlayışın izahı</h3>
              <hr>
              {% for word in word_e %}
            <div id="tab1-1{{word.id}}">
               <p>{{word.word_exp}}</p>
            </div>
              {% endfor %}
          </div>

      </div><!-- row -->
    </div>
</div>
<!-- A end-->




   </div>
</div>
</div>
<script>
    jQuery('ul.tabs').each(function(){
    // For each set of tabs, we want to keep track of
    // which tab is active and it's associated content
    var $active, $content, $links = jQuery(this).find('a');

    // If the location.hash matches one of the links, use that as the active tab.
    // If no match is found, use the first link as the initial active tab.
    $active = jQuery($links.filter('[href="'+location.hash+'"]')[0] || $links[0]);
    $active.addClass('active');

    $content = $($active[0].hash);

    // Hide the remaining content
    $links.not($active).each(function () {
        jQuery(this.hash).hide();
    });

    // Bind the click event handler
    jQuery(this).on('click', 'a', function(e){
        // Make the old tab inactive.
        $active.removeClass('active');
        $content.hide();

        // Update the variables with the new link and content
        $active = jQuery(this);
        $content = jQuery(this.hash);

        // Make the tab active.
        $active.addClass('active');
        $content.show();

        // Prevent the anchor's default click action
        e.preventDefault();
    });
});

</script>


{% include 'polls/footer.html' %}

templates/polls/oyren.html
{% load static %}
{% include 'polls/header.html' %}
<div id="learn_stat">
   <div class="container">
      <h1>Statistika öyrən</h1>
      <div class="v-tab">
         <div class="row">
            <div class="col-md-3 col-xs-12">
               <h4>Mövzular</h4>
               <ul class="v-tab_tab-head">
                        {% for tit in title %}
                  <li rel="{{tit.id}}">{{tit.title_l}}</li>
                  {% endfor %}

               </ul>
            </div>
            <div class="col-md-9 col-xs-12">
               <div class="v-tab_container">


                  <!-- #tab2 -->
                  {% for tit in title %}
                  <div id="{{tit.id}}" class="v-tab_content">
                     <h3>{{tit.content_l|safe}}</h3>
                     <hr>

                  </div>
{% endfor %}

               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<script>
   $(".v-tab_content").hide();
   $(".v-tab_content:first").show();

   $(".v-tab_tab-head li").click(function() {

     $(".v-tab_content").hide();
     var activeTab = $(this).attr("rel");
     $("#"+activeTab).fadeIn();
     $(".v-tab_tab-head li").removeClass("active");
     $(this).addClass("active");
   });


</script>
{% include 'polls/footer.html' %}

templates/polls/statistics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>